import random
from unidecode import unidecode
import enchant

title_list = ["Gloomhaven",
"Pandemic Legacy: Season 1",
"Brass: Birmingham",
"Gloomhaven: Jaws of the Lion",
"Terraforming Mars",
"Twilight Imperium: Fourth Edition",
"Gaia Project",
"Star Wars: Rebellion",
"Spirit Island",
"War of the Ring: Second Edition",
"Through the Ages: A New Story of Civilization",
"Great Western Trail",
"Twilight Struggle",
"Scythe",
"Dune: Imperium",
"The Castles of Burgundy",
"Nemesis",
"7 Wonders Duel",
"Concordia",
"Brass: Lancashire",
"Terra Mystica",
"A Feast for Odin",
"Wingspan",
"Arkham Horror: The Card Game",
"Root",
"Viticulture Essential Edition",
"Everdell",
"Orléans",
"Clank! Legacy: Acquisitions Incorporated",
"Mage Knight Board Game",
"Eclipse: Second Dawn for the Galaxy",
"Lost Ruins of Arnak",
"Ark Nova",
"Food Chain Magnate",
"Puerto Rico",
"Caverna: The Cave Farmers",
"Marvel Champions: The Card Game",
"Blood Rage",
"Too Many Bones",
"Barrage",
"Agricola",
"Maracaibo",
"Underwater Cities",
"Pandemic Legacy: Season 2",
"Pax Pamir: Second Edition",
"Mansions of Madness: Second Edition",
"The Crew: The Quest for Planet Nine",
"Anachrony",
"Tzolk'in: The Mayan Calendar",
"Power Grid",
"Clans of Caledonia",
"On Mars",
"Kingdom Death: Monster",
"Mechs vs. Minions",
"Le Havre",
"Star Wars: Imperial Assault",
"The 7th Continent",
"The Quacks of Quedlinburg",
"Crokinole",
"The Gallerist",
"Lisboa",
"Azul",
"Eclipse",
"Paladins of the West Kingdom",
"Aeon's End",
"Through the Ages: A Story of Civilization",
"Android: Netrunner",
"Pandemic Legacy: Season 0",
"Race for the Galaxy",
"Clank!: A Deck-Building Adventure",
"Fields of Arle",
"Robinson Crusoe: Adventures on the Cursed Island",
"Teotihuacan: City of Gods",
"Five Tribes",
"The Voyages of Marco Polo",
"7 Wonders",
"Agricola (Revised Edition)",
"Lords of Waterdeep",
"The Crew: Mission Deep Sea",
"Dominant Species",
"Grand Austria Hotel",
"Tainted Grail: The Fall of Avalon",
"Architects of the West Kingdom",
"Keyflower",
"El Grande",
"Cascadia",
"Caylus",
"Battlestar Galactica: The Board Game",
"Twilight Imperium: Third Edition",
"Troyes",
"Dominion: Intrigue",
"The Lord of the Rings: Journeys in Middle-Earth",
"Raiders of the North Sea",
"Mombasa",
"Eldritch Horror",
"Lorenzo il Magnifico",
"Kanban EV",
"Tigris and Euphrates",
"Patchwork",
"Rising Sun",
"Russian Railroads",
"The Isle of Cats",
"Decrypto",
"Trajan",
"Inis",
"Codenames",
"Dominion",
"Roll for the Galaxy",
"Clank! In! Space!: A Deck-Building Adventure",
"Aeon's End: War Eternal",
"Champions of Midgard",
"Cartographers",
"Trickerion: Legends of Illusion",
"Yokohama",
"Cthulhu: Death May Die",
"Pandemic",
"Pandemic: Iberia",
"Sleeping Gods",
"Sherlock Holmes Consulting Detective: The Thames Murders and Other Cases",
"Forbidden Stars",
"PARKS",
"Beyond the Sun",
"Kemet",
"Res Arcana",
"Vinhos Deluxe Edition",
"Endeavor: Age of Sail",
"Age of Steam",
"Alchemists",
"Targi",
"Star Realms",
"Legendary Encounters: An Alien Deck Building Game",
"Watergate",
"Stone Age",
"Star Wars: X-Wing Miniatures Game",
"It's a Wonderful World",
"Hansa Teutonica",
"Ticket to Ride: Europe",
"Welcome To",
"Istanbul",
"The Lord of the Rings: The Card Game",
"Azul: Summer Pavilion",
"That's Pretty Clever!",
"The Quest for El Dorado",
"Descent: Journeys in the Dark (Second Edition)",
"Just One",
"Chaos in the Old World",
"War of the Ring",
"Rajas of the Ganges",
"Xia: Legends of a Drift System",
"Concordia Venus",
"Obsession",
"Marco Polo II: In the Service of the Khan",
"Jaipur",
"Praga Caput Regni",
"Dead of Winter: A Crossroads Game",
"Memoir '44",
"Horrified",
"The Search for Planet X",
"The Resistance: Avalon",
"Viscounts of the West Kingdom",
"Magic: The Gathering",
"Railways of the World",
"Castles of Mad King Ludwig",
"Glen More II: Chronicles",
"Cosmic Encounter",
"Ora et Labora",
"A Game of Thrones: The Board Game (Second Edition)",
"This War of Mine: The Board Game",
"Dinosaur Island",
"Sagrada",
"Sekigahara: The Unification of Japan",
"Commands and Colors: Ancients",
"Suburbia",
"Ticket to Ride: Nordic Countries",
"Calico",
"Tyrants of the Underdark",
"Near and Far",
"Captain Sonar",
"Village",
"War Chest",
"Combat Commander: Europe",
"Nations",
"Star Realms: Colony Wars",
"Coimbra",
"Detective: A Modern Crime Board Game",
"Undaunted: Normandy",
"Paths of Glory",
"Codenames: Duet",
"Splendor",
"Go",
"Chronicles of Crime",
"Ra",
"Space Base",
"Dominion (Second Edition)",
"La Granja",
"Tichu",
"Carcassonne",
"Ticket to Ride",
"T.I.M.E Stories",
"Under Falling Skies",
"Cyclades",
"Legendary: A Marvel Deck Building Game",
"Zombicide: Black Plague",
"Kanban: Driver's Edition",
"YINSH",
"Dune",
"Santorini",
"Secret Hitler",
"Roll Player",
"Deception: Murder in Hong Kong",
"MicroMacro: Crime City",
"Terraforming Mars: Ares Expedition",
"Century: Golem Edition",
"Goa",
"The Princes of Florence",
"Sushi Go Party!",
"Dwellings of Eldervale",
"Hanamikoji",
"Nidavellir",
"Flamme Rouge",
"Modern Art",
"Arcadia Quest",
"Hero Realms",
"Isle of Skye: From Chieftain to King",
"Shogun",
"Galaxy Trucker",
"Viticulture",
"Steam",
"1830: Railways and Robber Barons",
"Aeon's End: Legacy",
"Glory to Rome",
"1960: The Making of the President",
"Lewis and Clark: The Expedition",
"The Taverns of Tiefenthal",
"Pulsar 2849",
"Samurai",
"Bora Bora",
"Too Many Bones: Undertow",
"Kingdomino",
"Seasons",
"My City",
"Dixit: Odyssey",
"Power Grid Deluxe: Europe/North America",
"Unmatched: Battle of Legends, Volume One",
"Star Wars: Outer Rim",
"Imperial",
"Rococo",
"KLASK",
"Western Legends",
"Dungeon Petz",
"Tapestry",
"Battle Line",
"Fantasy Realms",
"Fury of Dracula (Third/Fourth Edition)",
"The Manhattan Project: Energy Empire",
"Age of Empires III: The Age of Discovery",
"Paleo",
"Unmatched: Cobble and Fog",
"Imperial Settlers",
"Vindication",
"Space Alert",
"Navegador",
"Ethnos",
"Hive",
"Indonesia",
"Summoner Wars: Master Set",
"The Red Cathedral",
"Lords of Hellas",
"Onitama",
"Dead of Winter: The Long Night",
"Exit: The Game – The Abandoned Cabin",
"Runewars",
"Alien Frontiers",
"Cryptid",
"Imperial 2030",
"Antiquity",
"Nemo's War (Second Edition)",
"Burgle Bros",
"Telestrations",
"Century: Spice Road",
"BattleLore: Second Edition",
"Forgotten Waters",
"Cthulhu Wars",
"Hannibal: Rome vs. Carthage",
"Glass Road",
"Hallertau",
"Heaven and Ale",
"Tiny Epic Galaxies",
"Camel Up (Second Edition)",
"Arboretum",
"Tikal",
"Bruges",
"Small World",
"Above and Below",
"Dungeon Lords",
"Love Letter",
"Sid Meier's Civilization: The Board Game",
"Arkham Horror (Third Edition)",
"Mage Wars Arena",
"Acquire",
"Mysterium",
"Survive: Escape from Atlantis!",
"Letters from Whitechapel",
"Merchants and Marauders",
"Mission: Red Planet (Second Edition)",
"Bärenpark",
"Neuroshima Hex! 3.0",
"Dixit",
"The Resistance",
"Takenoko",
"Ankh: Gods of Egypt",
"Ghost Stories",
"Bunny Kingdom",
"Agricola: All Creatures Big and Small",
"Star Wars: Armada",
"Monikers",
"Awkward Guests",
"Altiplano",
"Harry Potter: Hogwarts Battle",
"Star Realms: Frontiers",
"For Sale",
"51st State: Master Set",
"Evolution: Climate",
"Lost Cities",
"San Juan",
"Here I Stand",
"Notre Dame",
"Tekhenu: Obelisk of the Sun",
"Die Macher",
"Nusfjord",
"At the Gates of Loyang",
"Gùgōng",
"The Pillars of the Earth",
"Gizmos",
"Blood Bowl: Team Manager – The Card Game",
"Dice Throne: Season Two – Battle Chest",
"Great Western Trail (Second Edition)",
"Endeavor",
"Bonfire",
"Saint Petersburg",
"Carpe Diem",
"Mythic Battles: Pantheon",
"Aeon's End: The New Age",
"Bruxelles 1893",
"In the Year of the Dragon",
"Innovation",
"Tiny Towns",
"Hadrian's Wall",
"Sherlock Holmes Consulting Detective: Jack the Ripper and West End Adventures",
"Azul: Stained Glass of Sintra",
"Ticket to Ride: Märklin",
"King of Tokyo",
"Newton",
"The Great Zimbabwe",
"Sword and Sorcery",
"Clash of Cultures",
"Abyss",
"Ginkgopolis",
"Pandemic: Fall of Rome",
"The Godfather: Corleone's Empire",
"Nippon",
"London (Second Edition)",
"San Juan (Second Edition)",
"Claustrophobia",
"Civilization",
"Downforce",
"Maria",
"Codenames: Pictures",
"Dune",
"Advanced Squad Leader",
"Destinies",
"Space Hulk (Third Edition)",
"Dice Forge",
"Chinatown",
"Twice as Clever!",
"Stockpile",
"Arkham Horror",
"Marvel United",
"Mice and Mystics",
"The King's Dilemma",
"Macao",
"Meadow",
"The Manhattan Project",
"Fresco",
"Thunderstone Quest",
"Santa Maria",
"Millennium Blades",
"Firefly: The Game",
"Flash Point: Fire Rescue",
"Spartacus: A Game of Blood and Treachery",
"Charterstone",
"Biblios",
"Sprawlopolis",
"A Few Acres of Snow",
"Point Salad",
"Anno 1800",
"Imperial Settlers: Empires of the North",
"Kingsburg",
"Lancaster",
"Schotten Totten",
"Blood Bowl: Living Rulebook",
"Quadropolis",
"Skull",
"Heroscape Master Set: Rise of the Valkyrie",
"Glen More",
"Pandemic: Reign of Cthulhu",
"Risk Legacy",
"Lord of the Rings: The Confrontation",
"Wavelength",
"Smartphone Inc",
"Amerigo",
"Pandemic: The Cure",
"BattleLore",
"Commands and Colors: Napoleonics",
"PitchCar",
"Sheriff of Nottingham",
"Amun-Re",
"Mystic Vale",
"Oath: Chronicles of Empire and Exile",
"Blood Bowl (Third Edition)",
"1775: Rebellion",
"Descent: Journeys in the Dark",
"Mansions of Madness",
"Forbidden Desert",
"Radlands",
"Shadows of Brimstone: City of the Ancients",
"Exit: The Game – Dead Man on the Orient Express",
"Raptor",
"Colt Express",
"Chess",
"Pipeline",
"Black Orchestra",
"Stuffed Fables",
"Labyrinth: The War on Terror, 2001 – ?",
"Deus",
"Citadels",
"Hanabi",
"Mandala",
"Shadows over Camelot",
"The King Is Dead: Second Edition",
"Citadels",
"Madeira",
"Catan",
"Middara: Unintentional Malum – Act 1",
"Lords of Vegas",
"Friday",
"Betrayal Legacy",
"Sidereal Confluence",
"BattleCON: Devastation of Indines",
"Skull King",
"Fire in the Lake",
"Freedom: The Underground Railroad",
"Junk Art",
"First Class: All Aboard the Orient Express!",
"London",
"Legends of Andor",
"Archipelago",
"Raiders of Scythia",
"Imhotep",
"Oceans",
"Small World Underground",
"Argent: The Consortium",
"The Grizzled",
"Euphoria: Build a Better Dystopia",
"Railroad Ink: Deep Blue Edition",
"Potion Explosion",
"Time's Up! Title Recall!",
"The Fox in the Forest",
"Cloudspire",
"King of Tokyo: Dark Edition",
"Roads and Boats",
"Sentinels of the Multiverse",
"Thurn and Taxis",
"Libertalia",
"Escape Plan",
"No Thanks!",
"Hadara",
"Ingenious",
"1846: The Race for the Midwest",
"One Night Ultimate Werewolf",
"TZAAR",
"Blackout: Hong Kong",
"Bohnanza",
"7 Wonders (Second Edition)",
"Egizia",
"Airlines Europe",
"Elysium",
"Port Royal",
"Queendomino",
"Kemet: Blood and Sand",
"RoboRally",
"Sushi Go!",
"Vikings",
"Vinhos",
"Tales of the Arabian Nights",
"Chicago Express",
"Runebound (Third Edition)",
"Last Will",
"Zombie Kidz Evolution",
"Pathfinder Adventure Card Game: Rise of the Runelords – Base Set",
"Alhambra",
"The Colonists",
"Karuba",
"Pax Porfiriana",
"Love Letter",
"Discworld: Ankh-Morpork",
"Taj Mahal",
"Photosynthesis",
"Baseball Highlights: 2045",
"StarCraft: The Board Game",
"Cubitos",
"Colosseum",
"Paperback",
"Love Letter Premium",
"Space Empires: 4X",
"Nexus Ops",
"Star Wars: X-Wing (Second Edition)",
"Camel Up",
"Furnace",
"Hammer of the Scots",
"DVONN",
"AquaSphere",
"Star Wars: X-Wing Miniatures Game – The Force Awakens Core Set",
"Unmatched: Robin Hood vs. Bigfoot",
"Blitzkrieg!: World War Two in 20 Minutes",
"Evolution",
"Dawn of the Zeds (Third Edition)",
"Automobile",
"Conan",
"Jamaica",
"Carson City",
"Valeria: Card Kingdoms",
"Francis Drake",
"Canvas",
"Blood Bowl (2016 Edition)",
"Broom Service",
"A Game of Thrones",
"Struggle of Empires",
"Through the Desert",
"Tobago",
"Carcassonne: Hunters and Gatherers",
"KeyForge: Call of the Archons",
"Las Vegas",
"Star Wars: Destiny",
"A Game of Thrones: The Card Game (Second Edition)",
"Nova Luna",
"Gears of War: The Board Game",
"Zombicide",
"Air, Land, and Sea",
"High Society",
"Silver and Gold",
"Quantum",
"Coup",
"Dice Throne: Season One",
"Mare Nostrum: Empires",
"In the Hall of the Mountain King",
"Thebes",
"The Republic of Rome",
"Snowdonia",
"Triumph and Tragedy: European Balance of Power 1936-1945",
"Imperium: Classics",
"Atlantis Rising (Second Edition)",
"The Battle of Five Armies",
"Earth Reborn",
"Pax Renaissance",
"Draftosaurus",
"Formula D",
"Cooper Island",
"Betrayal at House on the Hill",
"One Night Ultimate Werewolf: Daybreak",
"Trains",
"Magic Maze",
"Taluva",
"Time's Up!",
"Fantastic Factories",
"Star Trek: Ascendancy",
"Summoner Wars",
"Project L",
"Cuba Libre",
"Zombicide: Green Horde",
"Fleet: The Dice Game",
"Belfort",
"Shakespeare",
"Medici",
"Pan Am",
"Dixit: Journey",
"Coloretto",
"Mr. Jack",
"Shadows of Brimstone: Swamps of Death",
"Lord of the Rings: The Confrontation",
"The Downfall of Pompeii",
"Exit: The Game – The Pharaoh's Tomb",
"Kingdom Builder",
"Luna",
"Unlock!: Heroic Adventures",
"Thunderstone Advance: Towers of Ruin",
"Fort",
"Smash Up: Awesome Level 9000",
"Cuba",
"Cacao",
"Escape: The Curse of the Temple",
"Myrmes",
"HeroQuest",
"Elder Sign",
"Torres",
"6 nimmt!",
"Fury of Dracula (Second Edition)",
"Specter Ops",
"Between Two Castles of Mad King Ludwig",
"Leaving Earth",
"Defenders of the Realm",
"Tokaido",
"Feudum",
"Black Rose Wars",
"Honey Buzz",
"Yamataï",
"Crusaders: Thy Will Be Done",
"ZhanGuo",
"Warhammer Quest: The Adventure Card Game",
"Steampunk Rally",
"D-Day at Omaha Beach",
"Arkwright",
"Wallenstein",
"Tash-Kalar: Arena of Legends",
"Love Letter: Batman",
"Whitehall Mystery",
"Telestrations: 12 Player Party Pack",
"Advanced Squad Leader: Starter Kit #1",
"The Oracle of Delphi",
"The Networks",
"Prêt-à-Porter",
"BANG! The Dice Game",
"Vegas Showdown",
"Mexica",
"Aquatica",
"Wir sind das Volk!",
"Dragon Castle",
"Onirim (Second Edition)",
"Disney Villainous: Wicked to the Core",
"Imperial Struggle",
"Treasure Island",
"Ascension: Deckbuilding Game",
"City of the Big Shoulders",
"Century: Eastern Wonders",
"Ashes Reborn: Rise of the Phoenixborn",
"Civilization: A New Dawn",
"Cribbage",
"Shards of Infinity",
"My Little Scythe",
"Disney Villainous",
"Carcassonne: The Castle",
"K2",
"Middle-Earth Quest",
"Yspahan",
"Eminent Domain",
"Century: A New World",
"Between Two Cities",
"Shipyard",
"Churchill",
"Arcadia Quest: Inferno",
"Empires: Age of Discovery",
"Space Hulk: Death Angel – The Card Game",
"Up Front",
"Cry Havoc",
"Clash of Cultures: Monumental Edition",
"Space Hulk",
"The Duke",
"Diplomacy",
"A Fake Artist Goes to New York",
"AuZtralia",
"Coal Baron",
"Oh My Goods!",
"New Frontiers",
"Wits and Wagers",
"Reef",
"Zombicide Season 2: Prison Outbreak",
"Villagers",
"Descent: Legends of the Dark",
"The Estates",
"Ex Libris",
"Warhammer: Invasion",
"Caverna: Cave vs Cave",
"World Without End",
"Super Motherload",
"Kanagawa",
"Saint Petersburg (Second Edition)",
"1989: Dawn of Freedom",
"Disney Villainous: Evil Comes Prepared",
"Blue Moon City",
"Exit: The Game – The Secret Lab",
"Black Angel",
"Vast: The Crystal Caverns",
"Star Trek: Fleet Captains",
"CO₂: Second Chance",
"Deep Sea Adventure",
"Undaunted: North Africa",
"King of New York",
"Among the Stars",
"Q.E",
"Bus",
"Panamax",
"Trismegistus: The Ultimate Formula",
"878 Vikings: Invasions of England",
"Blokus",
"Washington's War",
"Finca",
"Summoner Wars: Alliances Master Set",
"Dungeons and Dragons: The Legend of Drizzt Board Game",
"Merv: The Heart of the Silk Road",
"Rhino Hero: Super Battle",
"FUSE",
"Squad Leader",
"Crystal Palace",
"Dogs of War",
"Vasco da Gama",
"Lords of Xidit",
"Tribune: Primus Inter Pares",
"Railroad Ink: Blazing Red Edition",
"Ticket to Ride: Rails and Sails",
"Heroes of Land, Air and Sea",
"Yedo",
"One Deck Dungeon",
"Tang Garden",
"Outlive",
"Jambo",
"The Pursuit of Happiness",
"Conflict of Heroes: Awakening the Bear! – Russia 1941-42",
"XCOM: The Board Game",
"Crown of Emara",
"Yellow and Yangtze",
"Fugitive",
"Combat Commander: Pacific",
"Perudo",
"Reef Encounter",
"13 Days: The Cuban Missile Crisis",
"The Mind",
"Ricochet Robots",
"ZÈRTZ",
"Trails of Tucana",
"Marvel Dice Masters: Avengers vs. X-Men",
"Not Alone",
"Red7",
"Napoleon's Triumph",
"Scoville",
"Spyfall",
"Gentes",
"Friedrich",
"Tajemnicze Domostwo",
"Star Wars: The Card Game",
"Empire of the Sun",
"Tinners' Trail",
"Chronicles of Crime: 1400",
"Spyrium",
"Carcassonne: The City",
"Can't Stop",
"Pandemic: Rising Tide",
"Celestia",
"Union Pacific",
"Dice Hospital",
"The Bloody Inn",
"Brew Crafters",
"Hyperborea",
"Detective: City of Angels",
"Unfair",
"Dale of Merchants",
"Sub Terra",
"Ca$h 'n Guns (Second Edition)",
"Warhammer Underworlds: Shadespire",
"Catacombs (Third Edition)",
"Tammany Hall",
"Diamant",
"Tumblin-Dice",
"New York Zoo",
"Thunderstone",
"The Magnificent",
"Menara",
"Signorie",
"Virgin Queen",
"Unlock!: Timeless Adventures",
"Santiago",
"The Palaces of Carrara",
"Morels",
"Summoner Wars (Second Edition)",
"Summoner Wars: Phoenix Elves vs Tundra Orcs",
"The Shipwreck Arcana",
"San Marco",
"Forbidden Island",
"Conflict of Heroes: Awakening the Bear! – Operation Barbarossa 1941 (Second Edition)",
"Legendary: A Marvel Deck Building Game – Villains",
"Akrotiri",
"Homesteaders",
"Rhino Hero",
"Roll Through the Ages: The Bronze Age",
"Last Night on Earth: The Zombie Game",
"Container",
"Wizard",
"Hannibal and Hamilcar",
"Bridge",
"The Lost Expedition",
"Genoa",
"Cerebria: The Inside World",
"Kitchen Rush",
"Whistle Mountain",
"Maharaja: The Game of Palace Building in India",
"Letter Jam",
"Pictomania",
"Louis XIV",
"Smash Up: Science Fiction Double Feature",
"Summoner Wars: Guild Dwarves vs Cave Goblins",
"Qwixx",
"Core Worlds",
"Heroscape Master Set: Swarm of the Marro",
"The Others",
"Project: ELITE",
"Thunder Alley",
"Tragedy Looper",
"Lanterns: The Harvest Festival",
"Battle for Rokugan",
"Palm Island",
"Web of Power",
"Wasteland Express Delivery Service",
"Dungeons and Dragons: Wrath of Ashardalon Board Game",
"Age of Industry",
"Boonlake",
"Mahjong",
"Britannia",
"Adrenaline",
"Hawaii",
"Ascension: Storm of Souls",
"Legacy: The Testament of Duke de Crecy",
"Last Bastion",
"Dream Factory",
"Red Rising",
"SpaceCorp: 2025-2300 AD",
"Parade",
"The Castles of Burgundy: The Card Game",
"Tiny Epic Quest",
"Jaws",
"Dungeons and Dragons: Castle Ravenloft Board Game",
"Attika",
"Zooloretto",
"Blue Lagoon",
"Concept",
"Call to Adventure",
"Snow Tails",
"Splendor: Marvel",
"5-Minute Dungeon",
"Werewords",
"IKI",
"Fabled Fruit",
"Flick 'em Up!",
"The City of Kings",
"Meeple Circus",
"Raccoon Tycoon",
"DC Comics Deck-Building Game",
"Lovecraft Letter",
"Etherfields",
"Bloodborne: The Board Game",
"Zombicide: Invader",
"Luxor",
"Qwirkle",
"DinoGenics",
"Tak",
"The Grimm Forest",
"Gold West",
"Istanbul: The Dice Game",
"Low Lands",
"La Città",
"Antike",
"Legendary Encounters: A Predator Deck Building Game",
"Ascension: Return of the Fallen",
"Disney Villainous: Perfectly Wretched",
"Coffee Roaster",
"Discoveries: The Journals of Lewis and Clark",
"Rurik: Dawn of Kiev",
"Paris: La Cité de la Lumière",
"Polis: Fight for the Hegemony",
"Marvel Dice Masters: Uncanny X-Men",
"Automobiles",
"Unfathomable",
"Detective Club",
"The Speicherstadt",
"Star Wars: The Queen's Gambit",
"History of the World",
"Kingsburg (Second Edition)",
"Space Hulk (Fourth Edition)",
"Mr. Jack Pocket",
"Zombicide Season 3: Rue Morgue",
"Star Trek: Frontiers",
"Condottiere",
"Santa Monica",
"Circadians: First Light",
"Railroad Revolution",
"Smash Up: Pretty Pretty Smash Up",
"Mint Works",
"Roam",
"Merchant of Venus (Second Edition)",
"World's Fair 1893",
"Manila",
"Valley of the Kings",
"Herbaceous",
"Black Fleet",
"CO2",
"Cottage Garden",
"Rivals for Catan",
"Majesty: For the Realm",
"Riverboat",
"Fields of Green",
"Wiz-War (Eighth Edition)",
"Firenze",
"Winner's Circle",
"Warhammer 40,000: Conquest",
"Empires of the Void II",
"Islebound",
"Falling Sky: The Gallic Revolt Against Caesar",
"Ticket to Ride: New York",
"Caylus 1303",
"Thunderstone: Dragonspire",
"Rex: Final Days of an Empire",
"Cartographers Heroes",
"Time of Crisis: The Roman Empire in Turmoil, 235-284 AD",
"Unmatched: Jurassic Park – InGen vs Raptors",
"Nations: The Dice Game",
"Cat Lady",
"A Distant Plain",
"A Study in Emerald",
"Ohanami",
"Smash Up: Monster Smash",
"Hey, That's My Fish!",
"Babylonia",
"Container: 10th Anniversary Jumbo Edition!",
"ICECOOL",
"BattleCON: War of Indines",
"Clinic: Deluxe Edition",
"Wildlands",
"Tide of Iron",
"Netrunner",
"Bitoku",
"NMBR 9",
"The Big Book of Madness",
"Dice Town",
"When I Dream",
"Tales and Games: The Hare and the Tortoise",
"Black Sonata",
"Loony Quest",
"Shikoku 1889",
"Reavers of Midgard",
"Via Nebula",
"Wilderness War",
"Zendo",
"Vinci",
"Batman: Gotham City Chronicles",
"Irish Gauge",
"The Lord of the Rings",
"Stronghold",
"Metropolys",
"Axis and Allies Anniversary Edition",
"Paper Tales",
"Fauna",
"Mr. Jack in New York",
"A War of Whispers",
"Terror in Meeple City",
"Archaeology: The New Expedition",
"Abomination: The Heir of Frankenstein",
"Tidal Blades: Heroes of the Reef",
"Shadowrun: Crossfire",
"Imperium: Legends",
"So Clover!",
"Era: Medieval Age",
"Smash Up",
"Dream Home",
"Linko!",
"Two Rooms and a Boom",
"Ikusa",
"China",
"Quartermaster General",
"Quarriors!",
"Runebound: Second Edition",
"Massive Darkness",
"Hardback",
"Ambush!",
"Diamonds: Second Edition",
"Battle Cry",
"Ghost Fightin' Treasure Hunters",
"Ecos: First Continent",
"Eight-Minute Empire: Legends",
"Orchard: A 9 card solitaire game",
"Zombicide: 2nd Edition",
"Battles of Westeros",
"Dominant Species: Marine",
"Unlock!: Epic Adventures",
"Explorers of the North Sea",
"Deep Space D-6",
"Warhammer Quest",
"Yggdrasil",
"Tiny Epic Dinosaurs",
"Tsuro",
"Honshū",
"Automania",
"Little Town",]

validWords = set(['CONCORDIA', 'DIXIT', 'MECHS', 'VOLK', 'SEKIGAHARA', 'DRAGONSPIRE', 'RULEBOOK', 'SPRAWLOPOLIS', 'BOONLAKE', 'WIR', 'MACHER', 'KEYFORGE', 'MAHAL', 'PICTOMANIA', 'THATS', 'BLOKUS', 'SCHOTTEN', 'CITTA', 'TERRAFORMING', 'DA', 'STARCRAFT', 'CHARTERSTONE', 'TAJ', 'MYRMES', 'ANACHRONY', 'SIND', 'DVONN', 'FINCA', 'KEMET', 'GINKGOPOLIS', 'GLOOMHAVEN', 'RAJAS', 'MORPORK', 'AQUASPHERE', 'QUARRIORS', 'PHOENIXBORN', 'FEUDUM', 'HYPERBOREA', 'CRAFTERS', 'EMARA', 'BATTLECON', 'TASH', 'DIAMANT', 'KANBAN', 'TINNERS', 'SHADESPIRE', 'ARKHAM', 'WATERDEEP', 'MEXICA', 'CAH', 'HEROQUEST', 'MEIERS', 'IL', 'SPEICHERSTADT', 'AUTOMANIA', 'DECKBUILDING', 'WILDLANDS', 'BATTLELORE', 'ICECOOL', 'MEEPLE', 'MIDDARA', 'DRAFTOSAURUS', 'JAMBO', 'WESTEROS', 'BATTLESTAR', 'ATTIKA', 'CO2', 'WARHAMMER', 'LIBRE', 'LABORA', 'MALUM', 'TARGI', 'CODENAMES', 'BLOODBORNE', 'SPYFALL', 'NIDAVELLIR', 'EGIZIA', 'SPACECORP', 'SAGRADA', 'CAYLUS', 'CELESTIA', 'AQUATICA', 'NIMMT', 'ANTIKE', 'MENARA', 'XIDIT', 'SCOVILLE', 'KEYFLOWER', 'NAPOLEONICS', 'CAVERNA', 'BITOKU', 'BARENPARK', 'NETRUNNER', 'MAHJONG', 'YINSH', 'EVERDELL', 'NAVEGADOR', 'WEREWORDS', 'TEUTONICA', 'RUNEBOUND', 'SIGNORIE', 'GUGONG', 'HANABI', 'QWIXX', 'GRANDE', 'LIBERTALIA', 'NOTRE', 'DOWNFORCE', 'NUSFJORD', 'RUNEWARS', 'FIGHTIN', 'CRYPTID', 'TAJEMNICZE', 'ROKUGAN', 'ARCHONS', 'MAHARAJA', 'RAVENLOFT', 'CUBITOS', 'YSPAHAN', 'TIKAL', 'MOTHERLOAD', 'AZUL', 'KLASK', 'METROPOLYS', 'QWIRKLE', 'ZOMBICIDE', 'HALLERTAU', 'AKROTIRI', 'VASCO', 'REAVERS', 'KALAR', 'TRISMEGISTUS', 'LISBOA', 'KINGDOMINO', 'QE', 'ARLE', 'TAKENOKO', 'GALACTICA', 'ZERTZ', 'PORFIRIANA', 'PERUDO', 'EV', 'ISLEBOUND', 'DAS', 'CORLEONES', 'PITCHCAR', 'DOMOSTWO', 'AD', 'NEMOS', 'CASCADIA', 'TIEFENTHAL', 'NMBR', 'INDINES', 'HEROSCAPE', 'CATAN', 'TZOLKIN', 'DISCWORLD', 'WASHINGTONS', 'TOTTEN', 'HANSA', 'TSURO', 'COLORETTO', 'MICROMACRO', 'DRIZZT'])

usDict = enchant.Dict("en_US")
ukDict = enchant.Dict("en_UK")

def getBoardGame():
    title = random.choice(title_list)
    title = unidecode(title)
    title = title.replace("-", " ")
    title = ''.join(ch for ch in title if ch.isalnum() or ch.isspace())
    title = title.strip()
    return title.split()

def getAllNonValidWords():
    allSpecialWords = set()
    for title in title_list:
        title = random.choice(title_list)
        title = unidecode(title)
        title = title.replace("-", " ")
        title = ''.join(ch for ch in title if ch.isalnum() or ch.isspace())
        title = title.strip()
        title = title.split()
        for word in title:
            print(word)
            if not (usDict.check(word) or ukDict.check(word)):
                if not word.isnumeric():
                    allSpecialWords.add(word.upper())

    print(allSpecialWords)

def isValidBoardGameWord(word):
    upperWord = word.upper()
    return usDict.check(upperWord) or ukDict.check(upperWord) or (upperWord in validWords) or upperWord.isnumeric()
