# import re
# import pinyin
import random

ALL_CHENG_YU = [
  ["不可得兼", ("bu", "ke", "de", "jian"), "You can't have both at the same time"],
  ["不得其法", ("bu", "de", "qi", "fa"), "Not knowing the right way"],
  ["心神不宁", ("xin", "shen", "bu", "ning"), "To feel bad about nothing"],
  ["一本正经", ("yi", "ben", "zheng", "jing"), "To always be serious"],
  ["沉鱼落雁", ("chen", "yu", "luo", "yan"), "Extremely beautiful"],
  ["独一无二", ("du", "yi", "wu", "er"), "Unique"],
  ["数一数二", ("shu", "yi", "shu", "er"), "The best; considered among the best"],
  ["绝无仅有", ("jue", "wu", "jin", "you"), "One of a kind; unique"],
  ["损人利己", ("sun", "ren", "li", "ji"), "To seek benefit at the expense of others"],
  ["幸灾乐祸", ("xing", "zai", "le", "huo"), "To enjoy others' misfortunes"],
  ["力不从心", ("li", "bu", "cong", "xin"), "The qualities aren't at the level of the aspirations"],
  ["亦步亦趋", ("yi", "bu", "yi", "qu"), "To blindly imitate someone"],
  ["滔滔不绝", ("tao", "tao", "bu", "jue"), "Without interruption"],
  ["省吃俭用", ("sheng", "chi", "jian", "yong"), "To live frugally"],
  ["婀娜多姿", ("e", "nuo", "duo", "zi"), "To be graceful"],
  ["应运而生", ("ying", "yun", "er", "sheng"), "To emerge thanks to a favorable situation"],
  ["厮守终生", ("si", "shou", "zhong", "sheng"), "To be together forever"],
  ["寓意深远", ("yu", "yi", "shen", "yuan"), "Morale is very low"],
  ["一切就绪", ("yi", "qie", "jiu", "xu"), "Everything is in order"],
  ["囫囵吞枣", ("hu", "lun", "tun", "zao"), "To swallow information without assimilating it"],
  ["塞翁失马", ("sai", "weng", "shi", "ma"), "Not all bad comes to cause harm"],
  ["狼吞虎咽", ("lang", "tun", "hu", "yan"), "To brush away food like a wolf"],
  ["避而不见", ("bi", "er", "bu", "jian"), "To avoid meeting someone"],
  ["成千上万", ("cheng", "qian", "shang", "wan"), "Thousands"],
  ["依依不舍", ("yi", "yi", "bu", "she"), "To be reluctant to leave something"],
  ["如期而至", ("ru", "qi", "er", "zhi"), "To arrive in time"],
  ["自作聪明", ("zi", "zuo", "cong", "ming"), "To be presumptuous"],
  ["废寝忘食", ("fei", "qin", "wang", "shi"), "Forgetting to eat and sleep so as to do something"],
  ["一门心思", ("yi", "men", "xin", "si"), "To be solely concentrated on doing something"],
  ["深情厚谊", ("shen", "qing", "hou", "yi"), "Long and intimate friendship"],
  ["死里逃生", ("si", "li", "tao", "sheng"), "To find a way out of certain death"],
  ["铺天盖地", ("pu", "tian", "gai", "di"), "To cover over everything"],
  ["与众不同", ("yu", "zhong", "bu", "tong"), "Different than the crowd"],
  ["心甘情愿", ("xin", "gan", "qing", "yuan"), "To be extremely happy to do something"],
  ["无可奈何", ("wu", "ke", "nai", "he"), "To have no alternatives/way out"],
  ["眼见为实", ("yan", "jian", "wei", "shi"), "To believe in what can be seen"],
  ["耳听为虚", ("er", "ting", "wei", "xu"), "To not believe in what you hear"],
  ["十全十美", ("shi", "quan", "shi", "mei"), "Perfect"],
  ["星火燎原", ("xing", "huo", "liao", "yuan"), "A single spark creates a blaze"],
  ["夸大其词", ("kua", "da", "qi", "ci"), "Exaggerate"],
  ["举目无亲", ("ju", "mu", "wu", "qin"), "To be a stranger in a strange land"],
  ["四海为家", ("si", "hai", "wei", "jia"), "To make every place your home; live as a hobo"],
  ["小心翼翼", ("xiao", "xin", "yi", "yi"), "Extremely cautious"],
  ["焕然一新", ("huan", "ran", "yi", "xin"), "To take on a completely new appearance"],
  ["乱七八糟", ("luan", "qi", "ba", "zao"), "In complete disorder"],
  ["不自觉地", ("bu", "zi", "jue", "di"), "Unconsciously"],
  ["筋疲力尽", ("jin", "pi", "li", "jin"), "To feel exhausted"],
  ["顺其自然", ("shun", "qi", "zi", "ran"), "To let nature take its course"],
  ["恋恋不舍", ("lian", "lian", "bu", "she"), "To be reluctant to leave"],
  ["擦肩而过", ("ca", "jian", "er", "guo"), "To brush up against someone in passing"],
  ["迫不及待", ("po", "bu", "ji", "dai"), "Impatiently waiting"],
  ["无所不谈", ("wu", "suo", "bu", "tan"), "To talk about everything under the sun"],
  ["不谋而合", ("bu", "mou", "er", "he"), "To agree without discussion"],
  ["不以为然", ("bu", "yi", "wei", "ran"), "To consider something unacceptable"],
  ["我行我素", ("wo", "xing", "wo", "su"), "To stick to your own way of doing things"],
  ["栩栩如生", ("xu", "xu", "ru", "sheng"), "As vivid as life"],
  ["莞尔一笑", ("guan", "er", "yi", "xiao"), "To give a faint smile"],
  ["胡说八道", ("hu", "shuo", "ba", "dao"), "To talk nonsense"],
  ["眉飞色舞", ("mei", "fei", "se", "wu"), "To be exultant, exuberant"],
  ["漫无目的", ("man", "wu", "mu", "de"), "To be without a goal"],
  ["左顾右盼", ("zuo", "gu", "you", "pan"), "To look to the left and right"],
  ["一针见血", ("yi", "zhen", "jian", "xie"), "To hit the mark"],
  ["轻而易举", ("qing", "er", "yi", "ju"), "Easy to do"],
  ["全心全意", ("quan", "xin", "quan", "yi"), "To do something with all your heart"],
  ["相去甚远", ("xiang", "qu", "shen", "yuan"), "To make a big difference"],
  ["彬彬有礼", ("bin", "bin", "you", "li"), "Sophisticated"],
  ["称兄道弟", ("cheng", "xiong", "dao", "di"), "To be like brothers with someone; to have a great relationship"],
  ["相提并论", ("xiang", "ti", "bing", "lun"), "To be placed at the same level of"],
  ["惟妙惟肖", ("wei", "miao", "wei", "xiao"), "To be just like the real thing"],
  ["忙里偷闲", ("mang", "li", "tou", "xian"), "To find time for pleasure between work"],
  ["全神贯注", ("quan", "shen", "guan", "zhu"), "Absorbed, absorbed in"],
  ["缘木求鱼", ("yuan", "mu", "qiu", "yu"), "To use counterproductive methods to do something"],
  ["见钱眼开", ("jian", "qian", "yan", "kai"), "To be desirous of money"],
  ["见利忘义", ("jian", "li", "wang", "yi"), "To forget integrity so as to achieve gain"],
  ["下不为例", ("xia", "bu", "wei", "li"), "It will not set a precedent"],
  ["可想而知", ("ke", "xiang", "er", "zhi"), "As you can well imagine"],
  ["不翼而飞", ("bu", "yi", "er", "fei"), "To suddenly disappear"],
  ["惊慌失措", ("liang", "huang", "shi", "cuo"), "Caught in panic"],
  ["龇牙咧嘴", ("zi", "ya", "lie", "zui"), "To grit your teeth in pain"],
  ["火上加油", ("huo", "shang", "jia", "you"), "To throw fuel on the fire"],
  ["雪上加霜", ("xue", "shang", "jia", "shuang"), "One disaster after another"],
  ["如愿以偿", ("ru", "yuan", "yi", "chang"), "Fully satisfied desires"],
  ["无理取闹", ("wu", "li", "qu", "nao"), "To create problems for no reason"],
  ["对牛弹琴", ("dui", "niu", "dan", "qin"), "To speak about someone"],
  ["理直气壮", ("li", "zhi", "qi", "zhuang"), "To do something while knowing you're in the right"],
  ["思前想后", ("si", "qian", "xiang", "hou"), "To accurately ponder over something"],
  ["如释重负", ("ru", "shi", "zhong", "fu"), "To feel freed of a great burden"],
  ["不可开交", ("bu", "ke", "kai", "jiao"), "Extremely (busy)"],
  ["重温旧梦", ("zhong", "wen", "jiu", "meng"), "To relive an old experience; relive an old dream"],
  ["兴致勃勃", ("xing", "zhi", "bo", "bo"), "Full of enthusiasm"],
  ["如影随形", ("ru", "ying", "sui", "xing"), "Inseparable; followed like your own shadow"],
  ["千言万语", ("qian", "yan", "wan", "yu"), "Thousands and thousands of words"],
  ["惴惴不安", ("zhui", "zhui", "bu", "an"), "On thorns"],
  ["大惊小怪", ("da", "liang", "xiao", "guai"), "Great fuss over something ordinary; to complain unjustifiably"],
  ["不足挂齿", ("bu", "zu", "gua", "chi"), "Nothing to talk about"],
  ["天涯海角", ("tian", "ya", "hai", "jiao"), "Far off worlds (expressing a very large distance"],
  ["垂垂老矣", ("chui", "chui", "lao", "yi"), "Always older"],
  ["白发苍苍", ("bai", "fa", "cang", "cang"), "From white hairs"],
  ["低三下四", ("di", "san", "xia", "si"), "Mean, petty"],
  ["安贫乐道", ("an", "pin", "le", "dao"), "Happy to live a virtuous life even if in a state of poverty"],
  ["光明磊落", ("guang", "ming", "lei", "luo"), "In broad daylight; cards showing; correctly and legitimately"],
  ["知足常乐", ("zhi", "zu", "chang", "le"), "To be content with what you have"],
  ["东山再起", ("dong", "shan", "zai", "qi"), "To stage a return"],
  ["完璧归赵", ("wan", "bi", "gui", "zhao"), "To give something back to its owner in excellent condition"],
  ["如虎添翼", ("ru", "hu", "tian", "yi"), "With double the power"],
  ["夜深人静", ("ye", "shen", "ren", "jing"), "In the silence of deepest night"],
  ["班门弄斧", ("ban", "men", "nong", "fu"), "To show your talent is of little account in front of a true expert on the material"],
  ["乘风破浪", ("cheng", "feng", "po", "lang"), "To have great ambitions"],
  ["程门立雪", ("cheng", "men", "li", "xue"), "To honor the master and respect his teachings"],
  ["狐假虎威", ("hu", "jia", "hu", "wei"), "To intimidate someone by flaunting your relationship with important people"],
  ["孟母三迁", ("meng", "mu", "san", "qian"), "A wise mother works to find a healthy educational environment for her children"],
  ["愚公移山", ("yu", "gong", "yi", "shan"), "To want to is to be able to"],
  ["画蛇添足", ("hua", "she", "tian", "zu"), "More than enough"],
  ["开卷有益", ("kai", "juan", "you", "yi"), "Reading always brings benefits"],
  ["世外桃源", ("shi", "wai", "tao", "yuan"), "Paradise if peace; utopia"],
  ["津津有味", ("jin", "jin", "you", "wei"), "To do something with gusto"],
  ["落英缤纷", ("luo", "ying", "bin", "fen"), "Flower petals that fall like snowflakes"],
  ["虚怀若谷", ("xu", "huai", "ruo", "gu"), "To be extremely open-minded"],
  ["心如止水", ("xin", "ru", "zhi", "shui"), "A peaceful heart; a heart as calm as still water"],
  ["随遇而安", ("sui", "yu", "er", "an"), "To feel adequate wherever you are"],
  ["厚德载物", ("hou", "de", "zai", "wu"), "To be of strong moral character"],
  ["大智若愚", ("da", "zhi", "ruo", "yu"), "The wise one appears stupid"],
  ["知行合一", ("zhi", "xing", "he", "yi"), "The union of practice and knowledge"],
  ["相濡以沫", ("xiang", "ru", "yi", "mo"), "To help each other out despite both being in delicate condition"],
  ["阳光明媚", ("yang", "guang", "ming", "mei"), "The sun is particularly bright"],
  ["忐忑不安", ("tan", "te", "bu", "an"), "Disquieted; preoccupied; uncomfortable"],
  ["说三道四", ("shuo", "san", "dao", "si"), "To gossip"],
  ["不顾一切", ("bu", "gu", "yi", "qie"), "Indifferent to everything"],
  ["开门见山", ("kai", "men", "jian", "shan"), "To get right to the chase"],
  ["一蹴而就", ("yi", "cu", "er", "jiu"), "To be successful on the first try"],
  ["惹是生非", ("re", "shi", "sheng", "fei"), "To start a dispute; begin a conflict"],
  ["安居乐业", ("an", "ju", "le", "ye"), "To live in peace, without disturbance"],
  ["难兄难弟", ("nan", "xiong", "nan", "di"), "Brothers of misfortune"],
  ["笑里藏刀", ("xiao", "li", "cang", "dao"), "A dagger hidden behind a smile"],
  ["海市蜃楼", ("hai", "shi", "shen", "lou"), "To build castles in the air; mirage"],
  ["厮守终身", ("si", "shou", "zhong", "shen"), "To be together for one's whole life"],
  ["伶牙俐齿", ("ling", "ya", "li", "chi"), "To be clear and eloquent"],
  ["日积月累", ("ri", "ji", "yue", "lei"), "To accumulate for a long time"],
  ["雷打不动", ("lei", "da", "bu", "dong"), "To be determined, unshakable"],
  ["家常便饭", ("jia", "chang", "bian", "fan"), "Routine"],
  ["一头雾水", ("yi", "tou", "wu", "shui"), "To feel confused"],
  ["大汗淋漓", ("da", "han", "lin", "li"), "To be soaked with sweat"],
  ["有条不紊", ("you", "tiao", "bu", "wen"), "Methodical, systematic"],
  ["知难而退", ("zhi", "nan", "er", "tui"), "To run from difficulty"],
  ["似懂非懂", ("si", "dong", "fei", "dong"), "To not fully understand"],
]


def getChengYu():
    return random.choice(ALL_CHENG_YU)
